// <auto-generated />
using System;
using Core_Providentia_vitae.Data.RH;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core_Providentia_vitae.Migrations
{
    [DbContext(typeof(RhContext))]
    partial class RhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Core_Providentia_vitae.Models.RH.CoordenadorSetor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CdCoordenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cd_coordenador")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("CdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cd_setor")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateTime>("DtCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dt_create")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DtFim")
                        .HasColumnType("date")
                        .HasColumnName("dt_fim");

                    b.Property<DateOnly?>("DtInicio")
                        .HasColumnType("date")
                        .HasColumnName("dt_inicio");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdCoordenador" }, "cd_coordenador");

                    b.HasIndex(new[] { "CdSetor" }, "setor");

                    b.ToTable("coordenador_setor", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.RH.CoordenadorUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CdCoordenador")
                        .HasColumnType("int")
                        .HasColumnName("cd_coordenador");

                    b.Property<int>("CdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("cd_funcionario");

                    b.Property<DateTime>("DtCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dt_create")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DtFim")
                        .HasColumnType("date")
                        .HasColumnName("dt_fim");

                    b.Property<DateOnly?>("DtInicio")
                        .HasColumnType("date")
                        .HasColumnName("dt_inicio");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdCoordenador" }, "cd_coordenador")
                        .HasDatabaseName("cd_coordenador1");

                    b.HasIndex(new[] { "CdFuncionario" }, "cd_funcionario");

                    b.ToTable("coordenador_usuario", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.RH.TrocaPlantao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CdSolicitante")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("cd_solicitante");

                    b.Property<int>("CdSubstituto")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("cd_substituto");

                    b.Property<DateOnly>("DtPlantaoOriginal")
                        .HasColumnType("date")
                        .HasColumnName("dt_plantao_original");

                    b.Property<DateOnly>("DtPlantaoTroca")
                        .HasColumnType("date")
                        .HasColumnName("dt_plantao_troca");

                    b.Property<DateTime?>("DtResposta")
                        .HasColumnType("datetime")
                        .HasColumnName("dt_resposta");

                    b.Property<DateTime?>("DtSolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dt_solicitacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeSpan>("HrEntradaPlantaoOriginal")
                        .HasColumnType("time")
                        .HasColumnName("hr_entrada_plantao_original");

                    b.Property<TimeSpan>("HrEntradaPlantaoTroca")
                        .HasColumnType("time")
                        .HasColumnName("hr_entrada_plantao_troca");

                    b.Property<TimeSpan>("HrSaidaPlantaoOriginal")
                        .HasColumnType("time")
                        .HasColumnName("hr_saida_plantao_original");

                    b.Property<TimeSpan>("HrSaidaPlantaoTroca")
                        .HasColumnType("time")
                        .HasColumnName("hr_saida_plantao_troca");

                    b.Property<string>("MotivoTroca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo_troca");

                    b.Property<string>("SnAceito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('S','N','P')")
                        .HasColumnName("sn_aceito")
                        .HasDefaultValueSql("'P'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DtPlantaoOriginal" }, "idx_dt_plantao_original");

                    b.HasIndex(new[] { "CdSolicitante" }, "idx_solicitante");

                    b.HasIndex(new[] { "CdSubstituto" }, "idx_substituto");

                    b.ToTable("troca_plantao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
