// <auto-generated />
using System;
using Core_Providentia_vitae.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core_Providentia_vitae.Data.Migrations.Mysql
{
    [DbContext(typeof(MysqlContext))]
    [Migration("20260601163608_TabelasMysqlContextCreate")]
    partial class TabelasMysqlContextCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Menu", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CdMenuPai")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("DtCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Ordem")
                        .HasColumnType("int unsigned");

                    b.Property<bool?>("SnAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nmMenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModulo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MenuId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ModuloId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("cd_Menu")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("cd_Modulo")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ModuloId");

                    b.ToTable("MenuModulo");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModuloPerfil", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MenuModuloId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PerfilId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("cdMenuModulo")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("cdPerfil")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("MenuModuloId");

                    b.HasIndex("PerfilId");

                    b.ToTable("MenuModuloPerfil");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Modulo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("DtCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NmModulos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("SnAtivo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Perfil", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("DsPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DtCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("SnAtivo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.UsuarioModulo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CdModulo")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CdUsuario")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ModuloId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioModulo");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Usuarios", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<int?>("Cracha")
                        .HasColumnType("int")
                        .HasColumnName("cracha");

                    b.Property<string>("Ds_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ds_usuario");

                    b.Property<DateTime?>("Dt_Create")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_create")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Dt_Log")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_log");

                    b.Property<DateTime?>("Dt_Ult_Log")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_ult_log");

                    b.Property<DateTime?>("Dt_Update")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_update");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<bool?>("Sn_Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("sn_ativo");

                    b.Property<bool?>("Sn_Funcionario")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sn_funcionario");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModulo", b =>
                {
                    b.HasOne("Core_Providentia_vitae.Models.Admin.Menu", "Menu")
                        .WithMany("MenuModulos")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_Providentia_vitae.Models.Admin.Modulo", "Modulo")
                        .WithMany("MenuModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModuloPerfil", b =>
                {
                    b.HasOne("Core_Providentia_vitae.Models.Admin.MenuModulo", "MenuModulo")
                        .WithMany("MenuModuloPerfils")
                        .HasForeignKey("MenuModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_Providentia_vitae.Models.Admin.Perfil", "Perfil")
                        .WithMany("MenuModuloPerfils")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuModulo");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.UsuarioModulo", b =>
                {
                    b.HasOne("Core_Providentia_vitae.Models.Admin.Modulo", "Modulo")
                        .WithMany("UsuarioModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_Providentia_vitae.Models.Usuarios", "Usuario")
                        .WithMany("UsuarioModulos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Menu", b =>
                {
                    b.Navigation("MenuModulos");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModulo", b =>
                {
                    b.Navigation("MenuModuloPerfils");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Modulo", b =>
                {
                    b.Navigation("MenuModulos");

                    b.Navigation("UsuarioModulos");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Perfil", b =>
                {
                    b.Navigation("MenuModuloPerfils");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Usuarios", b =>
                {
                    b.Navigation("UsuarioModulos");
                });
#pragma warning restore 612, 618
        }
    }
}
