// <auto-generated />
using System;
using Core_Providentia_vitae.Data.Admin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core_Providentia_vitae.Data.Migrations.Admin
{
    [DbContext(typeof(AdminContext))]
    [Migration("20260309115126_AdicionarMenuModuloEPerfil")]
    partial class AdicionarMenuModuloEPerfil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Menu", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DtCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_create")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool?>("SnAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("sn_ativo");

                    b.Property<string>("nmMenu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nmMenu");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModulo", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("cd_Menu")
                        .HasColumnType("int unsigned")
                        .HasColumnName("cd_menu");

                    b.Property<uint>("cd_Modulo")
                        .HasColumnType("int unsigned")
                        .HasColumnName("cd_modulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "cd_Menu" }, "IX_menu_modulos_cd_menu");

                    b.HasIndex(new[] { "cd_Modulo" }, "IX_menu_modulos_cd_modulo");

                    b.HasIndex(new[] { "cd_Menu" }, "cd_menu");

                    b.HasIndex(new[] { "cd_Modulo" }, "cd_modulo");

                    b.ToTable("menu_modulos", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Modulo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime?>("DtCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DtCreate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NmModulos")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nmModulos");

                    b.Property<bool?>("SnAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("snAtivo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("modulos", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Perfil", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("DsPefil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ds_perfil");

                    b.Property<DateTime?>("DtCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_create")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool?>("SnAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("sn_ativo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.UsuarioModulo", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("CdModulo")
                        .HasColumnType("int unsigned")
                        .HasColumnName("cd_modulo");

                    b.Property<uint>("CdUsuario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("cd_usuario");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdModulo" }, "cd_modulo")
                        .HasDatabaseName("cd_modulo1");

                    b.HasIndex(new[] { "CdUsuario" }, "cd_usuario");

                    b.ToTable("usuario_modulos", (string)null);
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Usuario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<int>("Cracha")
                        .HasColumnType("int");

                    b.Property<string>("Ds_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Dt_Create")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Dt_Log")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Dt_Ult_Log")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Dt_Update")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("Sn_Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Sn_Funcionario")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.MenuModulo", b =>
                {
                    b.HasOne("Core_Providentia_vitae.Models.Admin.Menu", "Menu")
                        .WithMany("MenuModulos")
                        .HasForeignKey("cd_Menu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_Providentia_vitae.Models.Admin.Modulo", "Modulo")
                        .WithMany("MenuModulos")
                        .HasForeignKey("cd_Modulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.UsuarioModulo", b =>
                {
                    b.HasOne("Core_Providentia_vitae.Models.Admin.Modulo", "Modulo")
                        .WithMany("UsuarioModulos")
                        .HasForeignKey("CdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_Providentia_vitae.Models.Usuario", "Usuario")
                        .WithMany("UsuarioModulos")
                        .HasForeignKey("CdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Menu", b =>
                {
                    b.Navigation("MenuModulos");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Admin.Modulo", b =>
                {
                    b.Navigation("MenuModulos");

                    b.Navigation("UsuarioModulos");
                });

            modelBuilder.Entity("Core_Providentia_vitae.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioModulos");
                });
#pragma warning restore 612, 618
        }
    }
}
